# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'untitled' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for untitled



  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'untitledTests' do
    inherit! :search_paths
    # Pods for testing
  end


    # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
    ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'






end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
